import { Chat } from "./chat"

export const metadata = {
  title: 'Tanjerin',
  description: 'Cook your next meal generated by AI!'
}

export default function Homepage() {
  return (
    <Chat />
  )
}
